### PR TITLE
Merge constructors with arguments

### PR DESCRIPTION
**Pull request by Lassebq**
There's no implementation for `@At("JUMP")` though.

### CODE REVIEW

**Comment by Geolykt** [comment]
The opcode would be best implemented as an InjectionPointConstraint implementation, which would allow us to avoid having to break ABI

**Comment by Lassebq** [comment]
In that case...

**Comment by Lassebq** [comment]
Will do opcode implementation later

**Comment by Lassebq** [comment]
If it's implemented via InjectionPointTargetConstraint I think you would be able apply opcode to any injection point. Not just FIELD and JUMP `@At`s as the docs in SpongePowered Mixin suggest
But in my opinion that's a good thing.

**Comment by Geolykt** [comment]
Thinking about it a bit more, this change would likely unearth issues with how the constructors are merged currently, that is local variables are not being duplicated.

Further, I'd like to have mixin's constructor merging semantics to be the default, while having the current micromixin constructor merging behaviour be explicitly opt-in (at least for the 0.6.X series this applies to only constructors with arguments [no-args constructors will have micromixins behaviour per default], where as with the 0.7.X series that would apply to all constructors).

Expect this change to how constructors are merged in the coming days (though I hope to do it today, but don't get your hopes all too high), in this meantime I will close this PR since I don't think I'll use your approach at all.

**Pull request closed without merging**
